
eureka:
  client:
    regitest-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: locahost

# Global variables
application:
  global:
    version: v1
